fastlane_version "2.168.0"

default_platform(:ios)

platform :ios do

  desc "Test all targets"
  lane :test do
    scan(
      workspace: "MovieDatabase.xcworkspace",
      scheme: "MovieDatabaseTests",
      device: "iPhone 12 Pro"
    )
  end
end
