# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies-Browser' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies-Browser
  pod 'SDWebImage'

  target 'Movies-BrowserTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Movies-BrowserUITests' do
    # Pods for testing
  end

end
