//
//  MainScreenWorker.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 23/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainScreenWorker
{
    
    let movieNetworkManager = MovieNetworkManager()
    let searchNetWorkManager = SearchNetworkManager()
    func doSomeWork()
    {
    }
    
    func fetchPopularMovies(request: MainScreen.FetchPopularMovies.Request, completion: @escaping (_ movies: [Movie]?,_ error: String?) -> ()){

        movieNetworkManager.getPopularMovies(page: request.index) { (movies, error) in
            if let error = error {
                completion(nil, error)
            }
            if let movies = movies {
                completion(movies, nil)
            }
        }
    }
    
    func fetchMoviesByQuery(request: MainScreen.FetchQueryMovies.Request, completion: @escaping (_ movies: [Movie]?,_ error: String?) -> ()) {
        searchNetWorkManager.getMoviesBy(query: request.text, page: request.index) { (movies, errorMessage) in
            if let error = errorMessage {
                completion(nil, error)
            }
            if let movies = movies {
                completion(movies, nil)
            }
        }
    }
}

