//
//  MainScreenModels.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 23/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Keys

enum MainScreen
{
    // MARK: Use cases
    
    struct ViewModel {
        struct MovieViewModel: Hashable {
            var posterUrl: String
            var title: String
        }
    }
    
    enum FetchPopularMovies {
        struct Request {
            var index: Int = 1
            init(index: Int) {
                self.index = index
            }
        }
    }
    
    enum FetchQueryMovies {
        struct Request {
            var index: Int = 1
            var text: String
        }
    }
}

