//
//  MainScreenRouter.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 23/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainScreenRoutingLogic {
    func routeToMovieDetail(shouldFilter: Bool, index: Int)
}

protocol MainScreenDataPassing {
    var dataStore: MainScreenDataStore? { get }
}

class MainScreenRouter: NSObject, MainScreenRoutingLogic, MainScreenDataPassing {
    weak var viewController: MainScreenViewController?
    var dataStore: MainScreenDataStore?

    // MARK: Routing

    func routeToMovieDetail(shouldFilter: Bool, index: Int) {
        guard let sourceVC = viewController else { return }
        let destinationVC = MovieDetailViewController()
        var destinationDataStore = destinationVC.router?.dataStore
        passDataToDetailScreen(source: dataStore, destination: &destinationDataStore, shouldFilter: shouldFilter, index: index)
        navigateToMovieDetail(source: sourceVC, destination: destinationVC)
    }

    func passDataToDetailScreen(source: MainScreenDataStore?, destination: inout MovieDetailDataStore?, shouldFilter: Bool, index: Int) {
        if shouldFilter {
            destination?.movie = source?.filteredMovies[index]
        } else {
            destination?.movie = source?.movies[index]
        }
    }

    func navigateToMovieDetail(source: MainScreenViewController, destination: MovieDetailViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
}
