# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecruitingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecruitingChallenge
	pod 'AlamofireImage', '~> 3.5'
	pod 'Alamofire', '~> 4.8'
	pod 'PromiseKit', '~> 6.8'
	pod 'RealmSwift'

end
