//
//  FilterMoviesInteractor.swift
//  Movs
//
//  Created by Brendoon Ryos on 06/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterMoviesBusinessLogic
{
  func doSomething(request: FilterMovies.Something.Request)
}

protocol FilterMoviesDataStore
{
  //var name: String { get set }
}

class FilterMoviesInteractor: FilterMoviesBusinessLogic, FilterMoviesDataStore
{
  var presenter: FilterMoviesPresentationLogic?
  var worker: FilterMoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FilterMovies.Something.Request)
  {
    worker = FilterMoviesWorker()
    worker?.doSomeWork()
    
    let response = FilterMovies.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
