//
//  FilterMoviesInteractor.swift
//  Movs
//
//  Created by Brendoon Ryos on 06/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterMoviesBusinessLogic {
  func fetchFilterValues(request: FilterMovies.Request)
}

protocol FilterMoviesDataStore {
  var genres: [String] { get set }
  var dates: [String] { get set }
}

class FilterMoviesInteractor: FilterMoviesBusinessLogic, FilterMoviesDataStore {
  var presenter: FilterMoviesPresentationLogic?
  var worker: FilterMoviesWorker?
  
  var genres: [String] = []
  var dates: [String] = []
  
  // MARK: Do something
  
  func fetchFilterValues(request: FilterMovies.Request) {
    let response = FilterMovies.Response.init(genres: genres, dates: dates)
    presenter?.presentFilterValues(response: response)
  }
}
