excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods

# rules that have both warning and error levels, can set just the warning level
# implicitly

# additionally they can set excluded names
identifier_name:
    min_length: # only min_length
        error: 2 # only error
    excluded: # excluded via string array
    - id
    - URL
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
