platform :ios, '13.0’
use_frameworks!
inhibit_all_warnings!

def common_pods

end

target 'ConcreteChallenge' do
  common_pods

  pod 'Moya', '~> 14.0'
end

target 'ConcreteChallengeTests' do
  common_pods
end

target 'ConcreteChallengeUITests' do
  common_pods
end