target 'ConcreteChallenge' do
  use_frameworks!
	pod 'Alamofire', '~> 4.7'
	pod 'SDWebImage', '~> 4.0'
	pod 'RealmSwift'
	

  target 'ConcreteChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConcreteChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
