# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-recruiting-brazil' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-recruiting-brazil

  target 'ios-recruiting-brazilTests' do
    inherit! :search_paths
    use_frameworks!
     pod 'SwiftLint'
  end

end
