//
//  ListFilmsWorker.swift
//  Movs
//
//  Created by Maisa on 22/10/18.
//  Copyright (c) 2018 Maisa Milena. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListFilmsWorker {
  func doSomeWork() {
    
  }
}
