workspace: Movs.xcworkspace
xcodeproj: Movs.xcodeproj
scheme: Movs
coverage_service: html
source_directory: "Movs"
output_directory: coverage_report
ignore:
  - ../**/*/Xcode*
  - ../core/*  
  - Pods/*
