os: osx
osx_image: xcode10
language: swift
podfile: Movs/

branches:
  only:
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods

script:
  - set -o pipefail
  - xcodebuild clean build test -project Movs/Movs.xcodeproj -scheme "Movs" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone 6s" ONLY_ACTIVE_ARCH=NO
