language: 
  - swift
osx_image: xcode11.4
env:
  global:
    - IOS_SDK=iphonesimulator13.4
script:
  - xcodebuild -workspace Movies-Browser/Movies-Browser.xcworkspace -scheme 'Movies-Browser' -sdk $IOS_SDK build analyze