# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'DesafioConcrete' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DesafioConcrete
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'DesafioConcreteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
