# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "concreto-filmes")
    slather(
      output_directory: "coverage",
      workspace: "concreto-filmes.xcworkspace",
      scheme: "concreto-filmes",
      proj: "concreto-filmes.xcodeproj",
      html: true
    )
  end
end
