# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DesafioIos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'

  # Pods for DesafioIos

  target 'DesafioIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DesafioIosUITests' do
    # Pods for testing
  end

end
