//
//  MovieDetailInteractor.swift
//  DataMovie
//
//  Created by Andre Souza on 14/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class MovieDetailInteractor {
    fileprivate let detailService = DetailService()
    fileprivate let addMovieService = AddMovieService()
}

// MARK: - Extensions -

extension MovieDetailInteractor: MovieDetailInteractorInterface {
    
    func getMovieDetail(tmdbID: Int, _ completion: @escaping (RequestResultType<MovieModel>) -> Void) {
        addMovieService.getMovieDetail(tmdbID: tmdbID, completion)
    }
    
    func downloadPoster(posterPath: String, _ completion: @escaping (DataResponse<Data>) -> Void) {
        addMovieService.downloadPosterImage(posterPath: posterPath, completion)
    }
    
    func getRecommendationsFor(movieID: Int, page: Int, _ completion: @escaping (RequestResultType<DiscoverMovieListModel>) -> Void) {
        detailService.get(movieID: movieID, page: page, completion)
    }
    
}
