//
//  ListFavoritesWorker.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

public let FavoritesKey = "favorites"

class ListFavoritesWorker {
	
	fileprivate let localPersistanceWorker = LocalPersistanceWorker()
	
	func fetchFavorites<T>(ofType: T.Type) -> [T]? where T : Decodable {
		return localPersistanceWorker.fetch(dataForKey: FavoritesKey, ofType: [T].self)
	}
	
	func saveToFavorites<T>(_ data: T) -> Bool where T : Codable {
		return localPersistanceWorker.saveToArray(data, withKey: FavoritesKey)
	}
	
}
