//
//  ListFavoritesPresenter.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListFavoritesPresentationLogic {
	func presentSomething(response: ListFavorites.Something.Response)
}

class ListFavoritesPresenter: ListFavoritesPresentationLogic {
	weak var viewController: ListFavoritesDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: ListFavorites.Something.Response) {
		let viewModel = ListFavorites.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
