//
//  ListFavoritesInteractor.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListFavoritesBusinessLogic {
	func doSomething(request: ListFavorites.Something.Request)
}

protocol ListFavoritesDataStore {
	//var name: String { get set }
}

class ListFavoritesInteractor: ListFavoritesBusinessLogic, ListFavoritesDataStore {
	var presenter: ListFavoritesPresentationLogic?
	var worker: ListFavoritesWorker?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: ListFavorites.Something.Request) {
		worker = ListFavoritesWorker()
		worker?.doSomeWork()
		
		let response = ListFavorites.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
