//
//  ListFavoritesModels.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListFavorites {
	// MARK: Use cases
	
	enum Something {
		struct Request {
			
		}
		struct Response {
			
		}
		struct ViewModel {
			
		}
	}
}
