//
//  ListFavoritesModels.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListFavorites {
	//MARK:- Get Favorites -
	
	struct MovieInfo {
		var id: Int
		var title: String
		var image: Data?
		var genres: [String]?
		var releaseDate: Date
		var overview: String
	}
	
	struct FormattedMovieInfo {
		var id: Int
		var title: String
		var image: UIImage?
		var genres: String?
		var release: String
		var overview: String
	}
	
	enum GetFavorites {
		struct Response {
			let isSuccess: Bool
			let movies: [MovieInfo]?
		}
		
		struct ViewModel {
			let isSuccess: Bool
			let moviesInfo: [FormattedMovieInfo]?
			let errorMessage: String?
		}
	}
}
