# Uncomment the next line to define a global platform for your project
 platform :ios, '12.4'

target 'Concrete Movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Concrete Movies
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'RealmSwift'
  pod 'SwiftSpinner'

end
