# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    gym(scheme: "Movs") # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Movs") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Movs")
    slather(
      output_directory: "coverage",
      workspace: "Movs.xcworkspace",
      scheme: "Movs",
      proj: "Movs.xcodeproj",
      html: true
    )
  end
end
