//
//  CoreDataManager.swift
//  Movs
//
//  Created by Tiago Chaves on 14/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation
import CoreData

class CoreDataManager{
    
    static let sharedInstance = CoreDataManager()
    private init() {}
    
    lazy var persistentContainer: NSPersistentContainer = {
        /*
         The persistent container for the application. This implementation
         creates and returns a container, having loaded the store for the
         application to it. This property is optional since there are legitimate
         error conditions that could cause the creation of the store to fail.
         */
        let container = NSPersistentContainer(name: "Movs")
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                
                /*
                 Typical reasons for an error here include:
                 * The parent directory does not exist, cannot be created, or disallows writing.
                 * The persistent store is not accessible, due to permissions or data protection when the device is locked.
                 * The device is out of space.
                 * The store could not be migrated to the current model version.
                 Check the error message to determine what the actual problem was.
                 */
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
        return container
    }()
    
    // MARK: - Core Data Saving support
    
    func saveContext () {
        let context = persistentContainer.viewContext
        if context.hasChanges {
            do {
                try context.save()
            } catch {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
                let nserror = error as NSError
                fatalError("Unresolved error \(nserror), \(nserror.userInfo)")
            }
        }
    }
    
    func createEntityObject(forEntity entity:String) -> NSManagedObject {
        
        return NSEntityDescription.insertNewObject(forEntityName: entity, into: self.persistentContainer.viewContext)
    }
    
    func getData<T>(ofEntity entityFetchRequest:NSFetchRequest<NSFetchRequestResult>, withPredicate predicate:NSPredicate?) -> [T] {
        
        let context = self.persistentContainer.viewContext
        let fetchRequest = entityFetchRequest
        
        if let predicate = predicate {
            
            fetchRequest.predicate = predicate
        }
        
        do {
            
            if let result = try context.fetch(fetchRequest) as? [T] {
                return result
            }
            return []
        }catch let err as NSError{
            NSLog("Error trying to fetch coredata -> \(err.description)")
        }
        
        return []
    }
    
    func deleteInCoreData<T:NSManagedObject>(object:T) -> Bool {
        
        var success = true
        
        let context = self.persistentContainer.viewContext
        context.delete(object)
        
        do {
            try context.save()
        } catch let error {
            success = false
            NSLog(error.localizedDescription)
        }
        
        return success
    }
    
    func deleteAllCoreData() -> Void{
        
        let managedContext = self.persistentContainer
        let names = managedContext.managedObjectModel.entities.map({ (entity) -> String in
            return entity.name ?? ""
        })
        
        for name in names{
            self.deleteAllData(ofEntity: name)
        }
    }
    
    func deleteAllData(ofEntity entity: String)
    {
        let managedContext = self.persistentContainer
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: entity)
        fetchRequest.returnsObjectsAsFaults = false
        
        do
        {
            let results = try managedContext.viewContext.fetch(fetchRequest)
            for managedObject in results
            {
                if let managedObjectData:NSManagedObject = managedObject as? NSManagedObject {
                    managedContext.viewContext.delete(managedObjectData)
                }
            }
            
            do {
                try managedContext.viewContext.save()
            } catch let error {
                NSLog(error.localizedDescription)
            }
        } catch let error as NSError {
            NSLog("Detele all data in \(entity) error : \(error) \(error.userInfo)")
        }
    }
    
    func applicationDocumentsDirectory() {
        if let url = FileManager.default.urls(for: .libraryDirectory, in: .userDomainMask).last {
            print(url.absoluteString)
        }
    }
}
