//
//  FavoriteMoviesModels.swift
//  Movs
//
//  Created by Tiago Chaves on 15/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavoriteMovies {
	
	// MARK: - Get Favorite Movies
	
	enum GetFavoriteMovies {
		
		struct Request {
			
		}
		
		struct Response {
			let favoriteMovies: [Movie]?
			let error: Error?
		}
		
		struct ViewModel {
			let favoriteMovies: [FavoriteMovieViewModel]?
			let error: Error?
		}
	}
	
	// MARK: - Unfavorite Movie
	
	enum UnfavoriteMovie {
		
		struct Request {
			let id:Int
		}
		
		struct Response {
			let success:Bool
		}
		
		struct ViewModel {
			let success:Bool
		}
	}
	
	// MARK: Show Movie Detail
	
	enum ShowMovieDetail {
		
		struct Request {
			let movieId: Int?
		}
		
		struct Response {
			
		}
		
		struct ViewModel {
			
		}
	}
}

struct FavoriteMovieViewModel {
	
	let id			:Int?
	let title		:String?
	let posterUrl	:String?
	let year		:String?
	let overview	:String?
}
