//
//  FavoriteMoviesRouter.swift
//  Movs
//
//  Created by Tiago Chaves on 15/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteMoviesRoutingLogic {
	func routeToFavoriteMovieDetail(segue: UIStoryboardSegue?)
}

protocol FavoriteMoviesDataPassing {
	var dataStore: FavoriteMoviesDataStore? { get }
}

class FavoriteMoviesRouter: NSObject, FavoriteMoviesRoutingLogic, FavoriteMoviesDataPassing {
	
	weak var viewController: FavoriteMoviesViewController?
	var dataStore: FavoriteMoviesDataStore?
	
	// MARK: - Routing
	
	func routeToFavoriteMovieDetail(segue: UIStoryboardSegue?) {
		
		if let segue = segue {

			let destinationVC = segue.destination as! MovieDetailViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToMovieDetail(source: dataStore!, destination: &destinationDS)
		}
	}

	// MARK: - Passing data
	
	func passDataToMovieDetail(source: FavoriteMoviesDataStore, destination: inout MovieDetailDataStore) {
		
		destination.movie = source.movie
	}
}
