//
//  AddMoviesInteractor.swift
//  DataMovie
//
//  Created by Andre Souza on 14/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import Alamofire

final class AddMoviesInteractor {
    fileprivate let addMovieService = AddMovieService()
    fileprivate let creditsService = CreditsService()
}

// MARK: - Extensions -

extension AddMoviesInteractor: AddMoviesInteractorInterface {
    
    func getMovieDetail(tmdbID: Int, _ completion: @escaping (RequestResultType<MovieModel>) -> Void) {
        addMovieService.getMovieDetail(tmdbID: tmdbID, completion)
    }
    
    func downloadPoster(posterPath: String, _ completion: @escaping (DataResponse<Data>) -> Void) {
        addMovieService.downloadPosterImage(posterPath: posterPath, completion)
    }
    
    func getCredits(tmdbID: Int, _ completion: @escaping (RequestResultType<CreditsModel>) -> Void) {
        creditsService.get(tmdbID: tmdbID, completion)
    }
    
}
