//
//  AddMoviesInterfaces.swift
//  DataMovie
//
//  Created by Andre Souza on 14/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Alamofire

enum AddMoviesNavigationOption {
}

protocol AddMoviesWireframeInterface: WireframeInterface {
    func navigate(to option: AddMoviesNavigationOption)
}

protocol AddMoviesViewInterface: ViewInterface {
    var selectedSegmentIndex: Int { get set }
    var activeViewController: UIViewController? { get set }
    func insertSegment(title: String, at index: Int)
}

protocol AddMoviesPresenterInterface: PresenterInterface {
    func initSegmentedViewControllers()
    func activeViewController(at index: Int) -> UIViewController
    func showSearchController()
    func findMovie(with title: String)
}

protocol AddMoviesInteractorInterface: InteractorInterface {
    func getMovieDetail(tmdbID: Int, _ completion: @escaping (RequestResultType<MovieModel>) -> Void)
    func downloadPoster(posterPath: String, _ completion: @escaping (DataResponse<Data>) -> Void)
    func getCredits(tmdbID: Int, _ completion: @escaping (RequestResultType<CreditsModel>) -> Void)
}

//Protocol for Search and discover viewcontrollers
protocol AddListsProtocol: class {
    var viewController: UIViewController { get }
    func updateItemStatus(with movieID: Int, isComplete: Bool)
}
