# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'concreto-filmes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 4.0.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftLint'
  # Pods for concreto-filmes
  def testing_pods
    pod 'Quick'
    pod 'Nimble'
  end

  target 'concreto-filmesTests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
  end

  target 'concreto-filmesUITests' do
    inherit! :search_paths
    # Pods for testing
    testing_pods
    pod 'KIF', :configurations => ['Debug']
  end

  plugin 'cocoapods-keys', {
  :project => "concreto-filmes",
  :keys => [
    "THE_MOVIE_DB_V3_KEY",
    "THE_MOVIE_DB_V4_READ_TOKEN",
  ]}
end
