# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Recruiting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'NVActivityIndicatorView', :inhibit_warnings => true
    # pod 'SKPhotoBrowser', :inhibit_warnings => true
    # pod 'AFDateHelper', :inhibit_warnings => true
    pod 'ObjectMapper', :inhibit_warnings => true
    pod 'Constraints', :inhibit_warnings => true
    pod 'Popover', :inhibit_warnings => true
    # pod 'Tags', :inhibit_warnings => true
    # pod 'SwiftyStoreKit', :inhibit_warnings => true


end
