# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wonder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wonder
  pod 'Kingfisher', '~> 4.0'

  target 'WonderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WonderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
