line_length: 240

type_name:
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 60
        error: 80

cyclomatic_complexity:
    ignores_case_statements: true
    warning: 5
    error: 6

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length: 20

file_length:
  warning: 410
  error: 420

force_try:
  severity: error # explicitly

disabled_rules:
    - function_body_length
    - identifier_name
    - large_tuple
    - type_body_length

opt_in_rules:
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - file_name
    - legacy_random
    - literal_expression_end_indentation
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - sorted_imports
    - static_operator
    - toggle_bool
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - unused_import
    - unused_private_declaration
    - yoda_condition
    - force_unwrapping
    - empty_count
    - fatal_error_message
    - first_where
    - last_where
    - void_return
    - type_name
    - syntactic_sugar
    - strict_fileprivate
    - no_fallthrough_only
    - colon
    - comma
    - conditional_returns_on_newline
    - contains_over_first_not_nil
    - control_statement
    - deployment_target
    - discouraged_direct_init
    - duplicate_imports
    - empty_enum_arguments
    - empty_parameters
    - empty_parentheses_with_trailing_closure
    - discouraged_object_literal
    - empty_string
    - legacy_constant
    - legacy_nsgeometry_functions
    - xctfail_message
    - weak_delegate
    - class_delegate_protocol
    - untyped_error_in_catch
    - valid_ibinspectable
    - anyobject_protocol

excluded:
    - Pods

