disabled_rules:
  - class_delegate_protocol
  - dynamic_inline
  - empty_parentheses_with_trailing_closure
  - private_unit_test
  - statement_position
  - type_body_length
  - unused_enumerated
  - valid_ibinspectable
  - unused_closure_parameter

excluded:
  - Pods

attributes:
  severity: error
closing_brace:
  severity: error
closure_end_indentation:
  severity: error
colon:
  severity: error
  flexible_right_spacing: false
  apply_to_dictionaries: true
comma:
  severity: error
conditional_returns_on_newline:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  - 10 #warning
  - 10 #error
empty_count:
  severity: error
empty_parameters:
  severity: error
explicit_init:
  severity: error
file_length:
  - 700 #warning
  - 700 #error
force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
function_body_length:
  - 300 #warning
  - 300 #error
function_parameter_count:
  - 8 #warning
  - 8 #error
implicit_getter:
  severity: error
large_tuple:
  - 3 #warning
  - 5 #error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_nsgeometry_functions:
  severity: error
line_length:
  - 120 #warning
  - 120 #error
mark:
  severity: error
nesting:
  severity: error
nimble_operator:
  severity: error
opening_brace:
  severity: error
operator_usage_whitespace:
  severity: error
operator_whitespace:
  severity: error
overridden_super_call:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
switch_case_on_newline:
  severity: error
syntactic_sugar:
  severity: error
todo:
  severity: error
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_name:
  severity: error
  max_length: 60
identifier_name:
  min_length: 2
  max_length: 60
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error