# Uncomment the next line to define a global platform for your project
platform :ios, '12.4'

target 'Movs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConcreteApplication
    pod 'Reusable', '~> 4.1'
    pod 'SDWebImage', '~> 5.1'
    pod 'SnapKit', '~> 5.0'
    pod 'RealmSwift', '~> 3.17'
    pod 'Swinject', '~> 2.6'
    pod 'SwiftLint', '~> 0.33'

  # Pods for Movs

  target 'MovsTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'OHHTTPStubs/Swift', '~> 8.0'
    pod 'iOSSnapshotTestCase', '~> 6.0'
  end

  target 'MovsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
