platform :ios, '9.0'

target 'movs' do
  use_frameworks!

pod 'SwiftLint'
pod 'Alamofire'
pod 'Kingfisher'
pod 'SwipeCellKit'

end

target 'movsUITests' do

pod 'SwiftLint'
pod 'Alamofire'
pod 'Kingfisher'
pod 'SwipeCellKit'

end
