# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movs
  pod 'CEPCombine', :git => 'https://github.com/IsaacDouglas/CEPCombine.git'

  target 'movsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
