//
//  PopularMoviesListModels.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PopularMoviesList {
	
	// MARK: Get popular movies
	
	enum GetPopularMovies {
		
		struct Request {
			let page:Int
		}
		
		struct Response {
			let result:PopularMoviesResult?
			let error:Error?
		}
		
		struct ViewModel {
			let movies:[MovieView]?
			let error:Error?
		}
	}
}

struct MovieView {
	
	let title		:String?
	let posterUrl	:String?
}
