//
//  PopularMoviesListInteractor.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesListBusinessLogic {
	func getPopularMovies(request: PopularMoviesList.GetPopularMovies.Request)
}

protocol PopularMoviesListDataStore {
	//var name: String { get set }
}

class PopularMoviesListInteractor: PopularMoviesListBusinessLogic, PopularMoviesListDataStore {
	
	var presenter: PopularMoviesListPresentationLogic?
	var worker: PopularMoviesListWorker?
	
	// MARK: - Get Popular Movies
	
	func getPopularMovies(request: PopularMoviesList.GetPopularMovies.Request) {
		
		worker = PopularMoviesListWorker(PopularMoviesNetworkWorker())
		worker?.getPopularMovies(request.page, completion: { (result, error) in

			var response:PopularMoviesList.GetPopularMovies.Response
			
			if error == nil {
				
				response = PopularMoviesList.GetPopularMovies.Response(result: result, error: nil)
			}else{
				
				response = PopularMoviesList.GetPopularMovies.Response(result: nil, error: error)
			}
			
			self.presenter?.presentPopularMovies(response: response)
		})
	}
}
