//
//  PopularMoviesListInteractor.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesListBusinessLogic {
	func doSomething(request: PopularMoviesList.Something.Request)
}

protocol PopularMoviesListDataStore {
	//var name: String { get set }
}

class PopularMoviesListInteractor: PopularMoviesListBusinessLogic, PopularMoviesListDataStore {
	
	var presenter: PopularMoviesListPresentationLogic?
	var worker: PopularMoviesListWorker?
	//var name: String = ""
	
	// MARK: Do something
	
	func doSomething(request: PopularMoviesList.Something.Request) {
		
//		worker = PopularMoviesListWorker()
//		worker?.doSomeWork()
		
		let response = PopularMoviesList.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
