//
//  PopularMoviesListViewController.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesListDisplayLogic: class {
	func displayPopularMovies(viewModel: PopularMoviesList.GetPopularMovies.ViewModel)
}

class PopularMoviesListViewController: UIViewController, PopularMoviesListDisplayLogic {
	
	var interactor: PopularMoviesListBusinessLogic?
	var router: (NSObjectProtocol & PopularMoviesListRoutingLogic & PopularMoviesListDataPassing)?
	
	// MARK: Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		
		let viewController = self
		let interactor = PopularMoviesListInteractor()
		let presenter = PopularMoviesListPresenter()
		let router = PopularMoviesListRouter()
		
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		
		if let scene = segue.identifier {
		
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		
		super.viewDidLoad()
		
		self.navigationController?.navigationBar.shadowImage = UIImage()
		
		getPopularMovies()
	}
	
	// MARK: - Outlets & Vars
	
	@IBOutlet weak var searchBar: UISearchBar!
	@IBOutlet weak var collectionView: UICollectionView!
	@IBOutlet weak var activityIndicator: UIActivityIndicatorView!
	
	let cellIdentifier = "MovieCell"
	var movies:[Movie] = []
	var nextPage = 1
	
	// MARK: - Get Popular Movies
	
	func getPopularMovies() {
		
		let request = PopularMoviesList.GetPopularMovies.Request()
		interactor?.getPopularMovies(request: request)
	}
	
	func displayPopularMovies(viewModel: PopularMoviesList.GetPopularMovies.ViewModel) {
		
	}
}

extension PopularMoviesListViewController: UICollectionViewDelegate, UICollectionViewDataSource {
	
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return movies.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		
		let movie = movies[indexPath.row]
		
		if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: cellIdentifier, for: indexPath) as? MovieCollectionViewCell {
			
			cell.config(withMovie: movie)
			
			return cell
		}
		
		return UICollectionViewCell()
	}
}
