//
//  PopularMoviesListRouter.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PopularMoviesListRoutingLogic {
	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PopularMoviesListDataPassing {
	var dataStore: PopularMoviesListDataStore? { get }
}

class PopularMoviesListRouter: NSObject, PopularMoviesListRoutingLogic, PopularMoviesListDataPassing {
	
	weak var viewController: PopularMoviesListViewController?
	var dataStore: PopularMoviesListDataStore?
	
	// MARK: Routing
	
//	func routeToSomewhere(segue: UIStoryboardSegue?) {
//		if let segue = segue {
//
//			let destinationVC = segue.destination as! SomewhereViewController
//			var destinationDS = destinationVC.router!.dataStore!
//			passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//		} else {
//
//			let storyboard = UIStoryboard(name: "Main", bundle: nil)
//			let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//			var destinationDS = destinationVC.router!.dataStore!
//			passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//			navigateToSomewhere(source: viewController!, destination: destinationVC)
//		}
//	}
//	
//	MARK: Navigation
//
//	func navigateToSomewhere(source: PopularMoviesListViewController, destination: SomewhereViewController) {
//		source.show(destination, sender: nil)
//	}
//
//	MARK: Passing data
//	
//	func passDataToSomewhere(source: PopularMoviesListDataStore, destination: inout SomewhereDataStore) {
//		destination.name = source.name
//	}
}
