//
//  PopularMoviesListRouter.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PopularMoviesListRoutingLogic {
	func routeToMovieDetail(segue: UIStoryboardSegue?)
}

protocol PopularMoviesListDataPassing {
	var dataStore: PopularMoviesListDataStore? { get }
}

class PopularMoviesListRouter: NSObject, PopularMoviesListRoutingLogic, PopularMoviesListDataPassing {
	
	weak var viewController: PopularMoviesListViewController?
	var dataStore: PopularMoviesListDataStore?
	
	// MARK: - Routing
	
	func routeToMovieDetail(segue: UIStoryboardSegue?) {
		
		if let segue = segue {

			let destinationVC = segue.destination as! MovieDetailViewController
			var destinationDS = destinationVC.router!.dataStore!
			passDataToMovieDetail(source: dataStore!, destination: &destinationDS)
		}
	}
	
	//MARK: - Passing data
	
	func passDataToMovieDetail(source: PopularMoviesListDataStore, destination: inout MovieDetailDataStore) {
		
		destination.movie = source.movie
	}
}
