//
//  PopularMoviesListPresenter.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesListPresentationLogic {
	func presentPopularMovies(response: PopularMoviesList.GetPopularMovies.Response)
	func presentMovieDetail(response: PopularMoviesList.ShowMovieDetail.Response)
}

class PopularMoviesListPresenter: PopularMoviesListPresentationLogic {
	
	weak var viewController: PopularMoviesListDisplayLogic?
	
	// MARK: - Get Popular Movies
	
	func presentPopularMovies(response: PopularMoviesList.GetPopularMovies.Response) {
		
		var viewModel:PopularMoviesList.GetPopularMovies.ViewModel
		
		if response.error == nil {
			
			let moviesView = getMoviesView(response.movies ?? [])
			viewModel = PopularMoviesList.GetPopularMovies.ViewModel(movies: moviesView, error: nil)
		}else{
			viewModel = PopularMoviesList.GetPopularMovies.ViewModel(movies: nil, error: response.error)
		}
	
		viewController?.displayPopularMovies(viewModel: viewModel)
	}
	
	private func getMoviesView(_ movies:[Movie]) -> [MovieViewModel] {
		
		var moviesView:[MovieViewModel] = []
		
		for movie in movies {
			
			let movieViewModel = MovieViewModel(id: movie.id,title: movie.title, posterUrl: movie.poster)
			moviesView.append(movieViewModel)
		}
		
		return moviesView
	}
	
	// MARK: - Show Movie Detail
	
	func presentMovieDetail(response: PopularMoviesList.ShowMovieDetail.Response) {
		
		let viewModel = PopularMoviesList.ShowMovieDetail.ViewModel()
		self.viewController?.displayMovieDetail(viewModel: viewModel)
	}
}
