//
//  PopularMoviesListPresenter.swift
//  Movs
//
//  Created by Tiago Chaves on 11/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PopularMoviesListPresentationLogic {
	func presentSomething(response: PopularMoviesList.Something.Response)
}

class PopularMoviesListPresenter: PopularMoviesListPresentationLogic {
	
	weak var viewController: PopularMoviesListDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: PopularMoviesList.Something.Response) {
		
		let viewModel = PopularMoviesList.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
