language: swift

osx_image: 
- xcode10.1
- xcode10.2

env:
- SCHEME=Kingfisher SWIFT_VERSION=5.0
- SCHEME=Kingfisher-macOS SWIFT_VERSION=5.0
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=5.0
- SCHEME=Kingfisher SWIFT_VERSION=4.2
- SCHEME=Kingfisher-macOS SWIFT_VERSION=4.2
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.2
- SCHEME=Kingfisher SWIFT_VERSION=4.0
- SCHEME=Kingfisher-macOS SWIFT_VERSION=4.0
- SCHEME=Kingfisher-tvOS SWIFT_VERSION=4.0

cache: bundler

before_install:
  - gem update --system
  - gem install bundler

matrix:
  exclude:
  - osx_image: xcode10.1
    env: SCHEME=Kingfisher SWIFT_VERSION=5.0
  - osx_image: xcode10.1
    env: SCHEME=Kingfisher-macOS SWIFT_VERSION=5.0
  - osx_image: xcode10.1
    env: SCHEME=Kingfisher-tvOS SWIFT_VERSION=5.0

script:
  - bundle exec fastlane test_ci
