//
//  FavoritesPresenter.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 31/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritesPresentationLogic {
  
}

class FavoritesPresenter: FavoritesPresentationLogic {
  weak var viewController: FavoritesDisplayLogic?
  
}
