//
//  FavoritesModels.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 31/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorites {
    
    struct ViewModel {
        struct movie {
            var title: String
            var overview: String
            var releaseYear: String
            var imageUrl: String
        }
    }
    
}
