//
//  DiscoverMoviesWireframe.swift
//  DataMovie
//
//  Created by Andre Souza on 24/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DiscoverMoviesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .discover)

    // MARK: - Module setup -

    init(discoverContent: DiscoverContent, addMoviesViewProtocol: AddMoviesProtocol) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DiscoverMoviesViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DiscoverMoviesInteractor()
        let presenter = DiscoverMoviesPresenter(wireframe: self, view: moduleViewController, interactor: interactor, discoverContent: discoverContent, addMoviesProtocol: addMoviesViewProtocol)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DiscoverMoviesWireframe: DiscoverMoviesWireframeInterface {

    func navigate(to option: DiscoverMoviesNavigationOption) {
    }
}
