disable_rules:
  - switch_case_alignment
  - unneeded_break_in_switch

excluded:
  - Pods

line_length:
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true
