# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'AlamofireImage'
  
  # Pods for app

  target 'appUITests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end

end

