//
//  FavoriteMoviesPresenter.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteMoviesPresentationLogic
{
  func presentSomething(response: FavoriteMovies.Something.Response)
}

class FavoriteMoviesPresenter: FavoriteMoviesPresentationLogic
{
  weak var viewController: FavoriteMoviesDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FavoriteMovies.Something.Response)
  {
    let viewModel = FavoriteMovies.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
