//
//  FavoriteMoviesWorker.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FavoriteMoviesWorker {
  
  private let databaseManager: DatabaseManager<CDMovie>
  
  init(databaseManager: DatabaseManager<CDMovie> = DatabaseManager<CDMovie>()) {
    self.databaseManager = databaseManager
  }
  
  func fetchFavoriteMovies(completion: @escaping ([CDMovie]) -> ()) {
    let movies = databaseManager.fetch()
    completion(movies)
  }
  
  func unfavoriteMovie(request: FavoriteMovies.Delete.Request, completion: @escaping ([CDMovie]) -> ()) {
    databaseManager.delete(object: request.movie)
    let movie = databaseManager.fetch()
    completion(movie)
  }
}
