//
//  FavoriteMoviesPresenter.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteMoviesPresentationLogic {
  func presentFavoriteMovies(response: FavoriteMovies.Show.Response)
  func presentErrorMessage(response: FavoriteMovies.Show.Response)
}

class FavoriteMoviesPresenter: FavoriteMoviesPresentationLogic {
  weak var viewController: FavoriteMoviesDisplayLogic?
  
  // MARK: Present Favorite Movies
  func presentFavoriteMovies(response: FavoriteMovies.Show.Response) {
    let viewModel = FavoriteMovies.Show.ViewModel(movies: response.movies)
    viewController?.displayFavoriteMovies(viewModel: viewModel)
  }
  
  // MARK: Present Error Message
  func presentErrorMessage(response: FavoriteMovies.Show.Response) {
    let viewModel = FavoriteMovies.Show.ViewModel(error: response.error)
    viewController?.displayErrorMessage(viewModel: viewModel)
  }
}
