//
//  FavoriteMoviesModels.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FavoriteMovies {
  // MARK: Use cases
  
  enum Show {
    struct Request {
      let query: String?
      let isFiltering: Bool
      
      init(query: String? = .none, isFiltering: Bool = false) {
        self.query = query
        self.isFiltering = isFiltering
      }
    }
    struct Response {
      let movies: [CDMovie]
      let error: ErrorType
      
      init(movies: [CDMovie] = [], error: ErrorType = .none) {
        self.movies = movies
        self.error = error
      }
    }
    struct ViewModel {
      let movies: [CDMovie]
      let error: ErrorType
      
      init(movies: [CDMovie] = [], error: ErrorType = .none) {
        self.movies = movies
        self.error = error
      }
    }
  }
  
  enum Delete {
    struct Request {
      let movie: CDMovie
      let isFiltering: Bool
      init(movie: CDMovie, isFiltering: Bool = false) {
        self.movie = movie
        self.isFiltering = isFiltering
      }
    }
    struct Response {}
    struct ViewModel {}
  }
  
  enum Filter {
    struct Request {
      let date: String
      let genre: String
    }
    struct Response {
      let movies: [CDMovie]
    }
    struct ViewModel {}
  }
  
}
