//
//  FavoriteMoviesInteractor.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteMoviesBusinessLogic
{
  func doSomething(request: FavoriteMovies.Something.Request)
}

protocol FavoriteMoviesDataStore
{
  //var name: String { get set }
}

class FavoriteMoviesInteractor: FavoriteMoviesBusinessLogic, FavoriteMoviesDataStore
{
  var presenter: FavoriteMoviesPresentationLogic?
  var worker: FavoriteMoviesWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: FavoriteMovies.Something.Request)
  {
    worker = FavoriteMoviesWorker()
    worker?.doSomeWork()
    
    let response = FavoriteMovies.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
