//
//  FavoriteMoviesRouter.swift
//  Movs
//
//  Created by Brendoon Ryos on 03/02/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteMoviesRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FavoriteMoviesDataPassing
{
  var dataStore: FavoriteMoviesDataStore? { get }
}

class FavoriteMoviesRouter: NSObject, FavoriteMoviesRoutingLogic, FavoriteMoviesDataPassing
{
  weak var viewController: FavoriteMoviesViewController?
  var dataStore: FavoriteMoviesDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: FavoriteMoviesViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: FavoriteMoviesDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
