//
//  Genre.swift
//  Movs
//
//  Created by Tiago Chaves on 12/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct Genre: Codable, Equatable, CustomStringConvertible {
	
    let id	: Int?
	let name: String?
	
    static func == (lhs: Genre, rhs: Genre) -> Bool {
    
        return lhs.id == rhs.id && lhs.name == rhs.name
    }
	
    var description: String {
        return "\(name ?? "-")"
    }
}
