//
//  Movie.swift
//  Movs
//
//  Created by Tiago Chaves on 12/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct Movie: Codable, Equatable, CustomStringConvertible {
	
    let title		: String?
	let poster		: String?
	let backdrop	: String?
	let date		: Date?
	let genre_ids	: [Int]?
	let overview	: String?
	let id			: Int?
	
    enum CodingKeys:String,CodingKey{
        
        case title
		case id
		case overview
		case genre_ids
		case poster 	= "poster_path"
		case backdrop 	= "backdrop_path"
		case date 		= "release_date"
    }
	
    static func == (lhs: Movie, rhs: Movie) -> Bool {
		
		return lhs.title == rhs.title && lhs.id == rhs.id
    }

    var description: String {
        return "\(title ?? "-")"
    }
	
	static func getMovieData(ofFavoriteMovies movies:[FavoriteMovie]) -> [Movie] {
		
		var moviesData:[Movie] = []
		
		for movie in movies {
			
			let movieData:Movie = Movie(title: movie.title,
										poster: movie.posterUrl,
										backdrop: movie.backdropUrl,
										date: movie.date as Date?,
										genre_ids: movie.genre_ids as? [Int] ?? [],
										overview: movie.overview,
										id: Int(movie.id))
			
			moviesData.append(movieData)
		}
		
		return moviesData
	}
}
