//
//  PersonDetailInteractor.swift
//  DataMovie
//
//  Created by Andre Souza on 14/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PersonDetailInteractor {
    fileprivate let personDetailService = PersonDetailService()
}

// MARK: - Extensions -

extension PersonDetailInteractor: PersonDetailInteractorInterface {
    
    func getDetail(personID: Int, _ completion: @escaping (RequestResultType<PersonDetailModel>) -> Void) {
        personDetailService.get(personID: personID, completion)
    }
    
}
