//
//  PersonDetailInterfaces.swift
//  DataMovie
//
//  Created by Andre Souza on 14/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PersonDetailNavigationOption {
}

protocol PersonDetailWireframeInterface: WireframeInterface {
    func navigate(to option: PersonDetailNavigationOption)
}

protocol PersonDetailViewInterface: ViewInterface {
    func showInfo(personDetail: PersonDetailView)
    func showError(error: ErrorInterface, target: Any, action: Selector)
    func showLoading(_ loading: Bool)
    func setBackgroundImage(_ image: UIImage?)
    func setCacheProfilePicture(_ image: UIImage?)
    func setName(_ name: String?)
}

protocol PersonDetailPresenterInterface: PresenterInterface {
    func touchFacebook()
    func touchTwitter()
    func touchInstagram()
    func touchIMDB()
    func touchHomepage()
    func loadPersonPicture(_ imageView: UIImageView)
}

protocol PersonDetailInteractorInterface: InteractorInterface {
    func getDetail(personID: Int, _ completion: @escaping (RequestResultType<PersonDetailModel>) -> Void)
}

protocol PersonDetailView {
    var birthdateFormatted: String? { get }
    var name: String? { get }
    var biography: String? { get }
    var homepage: String? { get }
    var externalIds: ExternalIDModel? { get }
}
