//
//  PersonDetailWireframe.swift
//  DataMovie
//
//  Created by Andre Souza on 14/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PersonDetailWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .personDetail)

    // MARK: - Module setup -

    init(personDetail: PersonDetailModel) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: PersonDetailViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = PersonDetailInteractor()
        let presenter = PersonDetailPresenter(wireframe: self, view: moduleViewController, interactor: interactor, personDetail: personDetail)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension PersonDetailWireframe: PersonDetailWireframeInterface {

    func navigate(to option: PersonDetailNavigationOption) {
    }
}
