# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "UI\ Tests")
  end
  
  desc "Run Unit Tests"
  lane :tests do
    run_tests(scheme: "Tests")
  end

  desc "Run UI Tests"
  lane :uitests do
    run_tests(scheme: "UI\ Tests")
  end
end