# Uncomment the lines below you want to change by removing the # in the beginning

devices([
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max"
])

languages([
  "en-US"
])

clear_previous_screenshots(true)
