# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sssss' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sssss

  target 'sssssTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sssssUITests' do
    # Pods for testing
  end

end
