# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConcreteFilmes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage'

  #pod 'Alamofire', '~> 5.2'
  #pod 'SwiftyJSON'
  #pod 'AlamofireImage'
  #pod 'Alamofire', '~> 5.2'

  # Pods for ConcreteFilmes


  target 'ConcreteFilmesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConcreteFilmesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end

