# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Mov' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mov
  pod 'Moya', '~> 11.0'
  pod 'SnapKit'
  pod 'Kingfisher', '~> 4.0'

  
  target 'MovTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
