# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Mov' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mov
  pod 'Moya', '~> 11.0'
  pod 'Quick'
  pod 'Nimble'

  target 'MovTests' do
    inherit! :search_paths
  end

end
