# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mov' do
  use_frameworks!

  pod ‘Alamofire’
  pod 'SwiftyJSON'
  pod 'ReachabilitySwift'
  pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  pod 'SDWebImage'

  target 'MovTests' do
    inherit! :search_paths
  end

end
