//
//  SearchMoviesWireframe.swift
//  DataMovie
//
//  Created by Andre on 26/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchMoviesWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .search)

    // MARK: - Module setup -

    init(addMoviesProtocol: AddMoviesProtocol) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: SearchMoviesViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = SearchMoviesInteractor()
        let presenter = SearchMoviesPresenter(wireframe: self, view: moduleViewController, interactor: interactor, addMoviesProtocol: addMoviesProtocol)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension SearchMoviesWireframe: SearchMoviesWireframeInterface {

    func navigate(to option: SearchMoviesNavigationOption) {
    }
}
