//
//  SearchMoviesViewController.swift
//  DataMovie
//
//  Created by Andre on 26/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class SearchMoviesViewController: DMBaseViewController {
    
    @IBOutlet private weak var tableView: UITableView! {
        didSet {
            setupTableView()
        }
    }
    
    @IBOutlet weak var tableViewFooter: UIView!
    @IBOutlet weak var footerLabel: UILabel!
    @IBOutlet weak var footerActivity: UIActivityIndicatorView!
    
    private let tableCellHeight: CGFloat = 115
    private var isLoading: Bool = false

    // MARK: - Public properties -

    var presenter: SearchMoviesPresenterInterface!
    var viewController: UIViewController {
        return self
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setup3Dtouch()
        presenter.viewDidLoad()
    }
	
}

// MARK: - Funcs -

extension SearchMoviesViewController {
    
    private func setupTableView() {
        tableView.register(MovieListTableViewCell.self)
        tableView.dataSource = self
        tableView.delegate = self
    }
    
    private func setup3Dtouch() {
        if(traitCollection.forceTouchCapability == .available){
            registerForPreviewing(with: self, sourceView: tableView)
        }
    }
    
}

// MARK: - Extensions -

extension SearchMoviesViewController: SearchMoviesViewInterface {
    
    func clearResults() {
        presenter.clearResults()
    }
    
    func findMovie(_ queryTitle: String) {
        presenter.findMovie(queryTitle)
    }
    
    func updateItemStatus(with movieID: Int, isComplete: Bool) {
        presenter.updateItemStatus(with: movieID, isComplete: isComplete)
    }
    
    func showFooterUpdatedMessage(message: String) {
        footerLabel.text = message
        footerActivity.isHidden = true
    }
    
    func reloadData(completion: (() -> ())?) {
        tableView.reloadData {
            completion?()
        }
    }
    
    func reloadData(at index: IndexPath) {
        tableView.reloadRows(at: [index], with: .none)
    }
    
    func showError(error: ErrorInterface, target: Any, action: Selector) {
        showFenceError(error: error, target: target, action: action)
    }
    
    func showFooterLoading(_ loading: Bool) {
        tableViewFooter.isHidden = !loading
    }
    
    func showTableviewLoading(_ loading: Bool) {
        isLoading = loading
        tableView.isUserInteractionEnabled = !loading
        tableView.reloadData()
    }
    
    func hideErrorView() {
        hideFenceView()
    }
    
}

// MARK: - UITableViewDataSource -

extension SearchMoviesViewController: UITableViewDataSource {
    
    func numberOfSections(in tableView: UITableView) -> Int {
        return presenter.numberOfSections()
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if isLoading {
            let loadingRows = ceil(tableView.bounds.height / tableCellHeight)
            return Int(loadingRows)
        }
        return presenter.numberOfItems(in: section)
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(forIndexPath: indexPath) as MovieListTableViewCell
        cell.isLoading = isLoading
        if !isLoading {
            presenter.loadPosterImage(cell.posterImage, at: indexPath)
            cell.item = presenter.discoverItem(at: indexPath)
            cell.tableViewProtocol = self
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return tableCellHeight
    }
    
}

// MARK: - UITableViewDelegate -

extension SearchMoviesViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: false)
        presenter.didSelectItem(at: indexPath)
    }
    
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        let lastElement = presenter.numberOfItems(in: indexPath.section) - 1
        if !tableViewFooter.isHidden && indexPath.row == lastElement {
            presenter.loadItems()
        }
    }
    
}

// MARK: - UIViewControllerPreviewingDelegate -

extension SearchMoviesViewController: UIViewControllerPreviewingDelegate {
    
    func previewingContext(_ previewingContext: UIViewControllerPreviewing, commit viewControllerToCommit: UIViewController) {
        show(viewControllerToCommit, sender: self)
    }
    
    func previewingContext(_ previewingContext: UIViewControllerPreviewing, viewControllerForLocation location: CGPoint) -> UIViewController? {
        guard let indexPath = tableView.indexPathForRow(at: location) else { return nil }
        previewingContext.sourceRect = tableView.rectForRow(at: indexPath)
        let detailVC = MovieListCellDetailViewController.newInstance(addProtocol: presenter, indexPath: indexPath)
        return detailVC
    }
    
}

// MARK: - AddMoviesTableViewProtocol -

extension SearchMoviesViewController: AddMoviesTableViewProtocol {
    
    func touchAddMovie(from row: UITableViewCell) {
        if let indexPath = tableView.indexPath(for: row) {
            presenter.addMovie(indexPath: indexPath)
        }
    }
    
}
