# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Challenge
  pod 'Alamofire', '~> 4.7'
  pod 'Kingfisher', '~> 4.0'

  target 'ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
