//
//  ListMoviesRouter.swift
//  Movs
//
//  Created by Lucas Ferraço on 15/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListMoviesRoutingLogic {
	func routeToSeeMovieDetails()
}

protocol ListMoviesDataPassing {
	var dataStore: ListMoviesDataStore? { get }
}

class ListMoviesRouter: NSObject, ListMoviesRoutingLogic, ListMoviesDataPassing {
	weak var viewController: ListMoviesViewController?
	var dataStore: ListMoviesDataStore?
	
	// MARK: Routing
	
	func routeToSeeMovieDetails() {
		let storyboard = UIStoryboard(name: "SeeMovieDetails", bundle: nil)
		let destinationVC = storyboard.instantiateViewController(withIdentifier: "SeeMovieDetailsViewController") as! SeeMovieDetailsViewController
		var destinationDS = destinationVC.router!.dataStore!
		passDataToSeeMovieDetails(source: dataStore!, destination: &destinationDS)
		navigateToSeeMovieDetails(source: viewController!, destination: destinationVC)
	}
	
	// MARK: Navigation
	
	func navigateToSeeMovieDetails(source: ListMoviesViewController, destination: SeeMovieDetailsViewController) {
	  source.navigationController?.pushViewController(destination, animated: true)
	}
	
	// MARK: Passing data
	
	func passDataToSeeMovieDetails(source: ListMoviesDataStore, destination: inout SeeMovieDetailsDataStore) {
		destination.movie = source.selectedMovie
		destination.isFavorite = source.isFavorite
	}
}
