//
//  ListMoviesViewController.swift
//  Movs
//
//  Created by Lucas Ferraço on 15/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesDisplayLogic: class {
	func displayMovieList(with viewModel: ListMovies.GetMovies.ViewModel)
}

class ListMoviesViewController: UIViewController, ListMoviesDisplayLogic {
	var interactor: ListMoviesBusinessLogic?
	var router: (NSObjectProtocol & ListMoviesRoutingLogic & ListMoviesDataPassing)?
	
	fileprivate var collectionManager: MovieCollectionViewManager!
	fileprivate var refreshControl: UIRefreshControl!
	
	@IBOutlet weak var moviesCollectionView: UICollectionView!
	
	// MARK: Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = ListMoviesInteractor()
		let presenter = ListMoviesPresenter()
		let router = ListMoviesRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		setupMoviesCollection()
		getUpcomingMovies()
	}
	
	// MARK: ListMoviesDisplayLogic implementation
	
	func displayMovieList(with viewModel: ListMovies.GetMovies.ViewModel) {
		if refreshControl.isRefreshing {
			refreshControl.endRefreshing()
		}
		
		if let moviesInfo = viewModel.moviesInfo {
			collectionManager.display(movies: moviesInfo)
		} else if let message = viewModel.errorMessage {
			let alert = UIAlertController(title: "Ops", message: message, preferredStyle: .alert)
			alert.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
			
			self.present(alert, animated: true, completion: nil)
		}
	}
	
	//MARK:- Auxiliary Methods
	
	@objc fileprivate func getUpcomingMovies() {
		if !refreshControl.isRefreshing {
			refreshControl.beginRefreshing()
		}
		
		interactor?.getMovies()
	}
	
	fileprivate func setupMoviesCollection() {
		moviesCollectionView.contentInset = UIEdgeInsets(top: 20, left: 5, bottom: 0, right: 5)
		moviesCollectionView.alwaysBounceVertical = true
		
		refreshControl = UIRefreshControl()
		refreshControl.addTarget(self, action: #selector(getUpcomingMovies), for: .valueChanged)
		moviesCollectionView.refreshControl = refreshControl
		
		setupMoviewCollectionManager()
	}
	
	fileprivate func setupMoviewCollectionManager() {
		collectionManager = MovieCollectionViewManager(of: moviesCollectionView)
		collectionManager.delegate = self
		collectionManager.cellDelegate = self
		
		moviesCollectionView.dataSource = collectionManager
		moviesCollectionView.delegate = collectionManager
	}
}

//MARK: - MovieCollectionViewCellProtocol -

extension ListMoviesViewController: MovieCollectionViewCellProtocol {
	func image(forMovieId id: Int, _ completion: @escaping (UIImage) -> Void) {
		DispatchQueue.main.async {
			self.interactor?.getImage(forMovieId: id, completion)
		}
	}
}

//MARK: - MovieCollectionViewManagerProtocol -

extension ListMoviesViewController: MovieCollectionViewManagerProtocol {	
	func getMoreMovies(_ completion: @escaping ([ListMovies.FormattedMovieInfo]) -> Void) {
		
	}
	
	func didSelectMovie(with id: Int) {
		
	}
	
	func didFavoritedMovie(withId id: Int) {
		
	}
}
