//
//  ListMoviesViewController.swift
//  Movs
//
//  Created by Lucas Ferraço on 15/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListMoviesDisplayLogic: class {
	func displayMovieList(with viewModel: ListMovies.GetMovies.ViewModel)
    func displayUpdatedMovies(with viewModel: ListMovies.UpdateMovies.ViewModel)
}

class ListMoviesViewController: UIViewController, ListMoviesDisplayLogic {
	var interactor: ListMoviesBusinessLogic?
	var router: (NSObjectProtocol & ListMoviesRoutingLogic & ListMoviesDataPassing)?
	
	fileprivate var collectionManager: MovieCollectionViewManager!
	fileprivate var refreshControl: UIRefreshControl!
    
	@IBOutlet weak var moviesCollectionView: UICollectionView!
    @IBOutlet weak var errorLabel: UILabel!
    
	// MARK: Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = ListMoviesInteractor()
		let presenter = ListMoviesPresenter()
		let router = ListMoviesRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		
		setupMoviesCollection()
		getUpcomingMovies()
	}
	
	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		
		tabBarController?.tabBar.isHidden = false
        changeScrollOrientation(to: UIApplication.shared.statusBarOrientation)
        
		interactor?.updateFavorites()
	}
    
    override func willRotate(to toInterfaceOrientation: UIInterfaceOrientation, duration: TimeInterval) {
        changeScrollOrientation(to: toInterfaceOrientation)
    }
	
	// MARK: ListMoviesDisplayLogic implementation
	
	func displayMovieList(with viewModel: ListMovies.GetMovies.ViewModel) {
		if refreshControl.isRefreshing {
			refreshControl.endRefreshing()
		}
		
		if let moviesInfo = viewModel.moviesInfo {
            errorLabel.isHidden = true
            moviesCollectionView.isHidden = false
            
			collectionManager.display(movies: moviesInfo)
		} else if let message = viewModel.errorMessage {
			errorLabel.isHidden = false
            moviesCollectionView.isHidden = true
            
            errorLabel.text = message
		}
	}
    
    func displayUpdatedMovies(with viewModel: ListMovies.UpdateMovies.ViewModel) {
        collectionManager.updateInfo(forMovies: viewModel.moviesInfo)
    }
	
	//MARK:- Auxiliary Methods
	
	@objc fileprivate func getUpcomingMovies() {
		if !refreshControl.isRefreshing {
			refreshControl.beginRefreshing()
		}
		
		interactor?.getMovies()
	}
	
	fileprivate func setupMoviesCollection() {
		moviesCollectionView.contentInset = UIEdgeInsets(top: 5, left: 5, bottom: 10, right: 5)
        
		refreshControl = UIRefreshControl()
		refreshControl.addTarget(self, action: #selector(getUpcomingMovies), for: .valueChanged)
		moviesCollectionView.refreshControl = refreshControl
		
		setupMoviewCollectionManager()
	}
	
	fileprivate func setupMoviewCollectionManager() {
		collectionManager = MovieCollectionViewManager(of: moviesCollectionView)
		collectionManager.delegate = self
		collectionManager.cellDelegate = self
		
		moviesCollectionView.dataSource = collectionManager
		moviesCollectionView.delegate = collectionManager
	}
    
    fileprivate func changeScrollOrientation(to interfaceOrientation: UIInterfaceOrientation) {
        guard let layout = moviesCollectionView.collectionViewLayout as? UICollectionViewFlowLayout else { return }
        
        if interfaceOrientation == .landscapeLeft || interfaceOrientation == .landscapeRight {
            layout.scrollDirection = .horizontal
        } else {
            layout.scrollDirection = .vertical
        }
    }
}

//MARK: - MovieCollectionViewCellProtocol -

extension ListMoviesViewController: MovieCollectionViewCellProtocol {
	func image(forMovieId id: Int, _ completion: @escaping (UIImage) -> Void) {
		DispatchQueue.main.async {
			self.interactor?.getImage(forMovieId: id, completion)
		}
	}
}

//MARK: - MovieCollectionViewManagerProtocol -

extension ListMoviesViewController: MovieCollectionViewManagerProtocol {	
	func getMoreMovies(_ completion: @escaping ([ListMovies.FormattedMovieInfo]) -> Void) {
		
	}
	
	func didSelectMovie(with id: Int) {
		interactor?.setSelectedMovie(with: id)
		router?.routeToSeeMovieDetails()
	}
	
	func didFavoritedMovie(withId id: Int) {
		interactor?.favoriteMovie(with: id)
	}
}
