//
//  ListMoviesModels.swift
//  Movs
//
//  Created by Lucas Ferraço on 15/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListMovies {
	
	enum RequestError: Error {
		case NoConnection, Failure
	}
	
	//MARK:- Get Movies -
	
	struct MovieInfo {
		var id: Int
		var title: String
		var image: Data?
		var genres: [String]
		var releaseDate: Date
	}
	
	struct FormattedMovieInfo {
		var id: Int
		var title: String
		var image: UIImage?
		var mainGenre: String?
		var release: String
	}
	
	enum GetMovies {
		struct Response {
			let isSuccess: Bool
			let error: RequestError?
			let movies: [MovieInfo]?
		}
		
		struct ViewModel {
			let isSuccess: Bool
			let moviesInfo: [FormattedMovieInfo]?
			let errorMessage: String?
		}
	}
}
