//
//  PopularMoviesListInteractorTests.swift
//  Movs
//
//  Created by Tiago Chaves on 18/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movs
import XCTest

class PopularMoviesListInteractorTests: XCTestCase {
	
	// MARK: System under test
	
	var sut: PopularMoviesListInteractor!
	
	// MARK: Test lifecycle
	
	override func setUp() {
		
		super.setUp()
		setupPopularMoviesListInteractor()
	}
	
	override func tearDown() {
		
		super.tearDown()
	}
	
	// MARK: Test setup
	
	func setupPopularMoviesListInteractor() {
		
		sut = PopularMoviesListInteractor()
	}
	
	// MARK: Test doubles
	
	class PopularMoviesListPresentationLogicSpy: PopularMoviesListPresentationLogic {
		
		var presentPopularMoviesCalled = false
		var presentMovieDetailsCalled = false
		var presentFilteredMoviesCalled = false
		var presentFavoritedMoviesCalled = false
		
		func presentPopularMovies(response: PopularMoviesList.GetPopularMovies.Response) {
			presentPopularMoviesCalled = true
		}
		
		func presentMovieDetail(response: PopularMoviesList.ShowMovieDetail.Response) {
			presentMovieDetailsCalled = true
		}
		
		func presentFilteredMovies(response: PopularMoviesList.FilteredMovies.Response) {
			presentFilteredMoviesCalled = true
		}
		
		func presentFavoritedMovies(response: PopularMoviesList.RefreshFavoriteStatus.Response) {
			presentFavoritedMoviesCalled = true
		}
	}
	
	class PopularMoviesListWorkerSpy: PopularMoviesListWorker {
		
		var getPopularMoviesCalled = false
		
		override func getPopularMovies(_ page: Int, completion: @escaping (PopularMoviesResult?, Error?) -> Void) {
			
			getPopularMoviesCalled = true
			completion(nil,nil)
		}
	}
	
	class GenresWorkerSpy: GenresWorker {
		
		var getGenresListCalled = false
		
		override func getGenresList(completionHandler: @escaping ([GenreData]?, Error?) -> Void) {
			
			getGenresListCalled = true
			completionHandler(nil,nil)
		}
	}
	
	// MARK: Tests
	
	func testInteractor_isCallingWorkerToGetPopularMovies() {
		
		let workerSpy = PopularMoviesListWorkerSpy(PopularMoviesNetworkWorker())
		sut.worker = workerSpy
		let request = PopularMoviesList.GetPopularMovies.Request(page: 1)
		
		sut.getPopularMovies(request: request)
		
		XCTAssertTrue(workerSpy.getPopularMoviesCalled)
	}
}
