//
//  PopularMoviesListWorkerTests.swift
//  Movs
//
//  Created by Tiago Chaves on 18/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movs
import XCTest

class PopularMoviesListWorkerTests: XCTestCase
{
	// MARK: System under test
	
	var sut: PopularMoviesListWorker!
	
	// MARK: Test lifecycle
	
	override func setUp() {
		
		super.setUp()
		setupPopularMoviesListWorker()
	}
	
	override func tearDown() {
		
		super.tearDown()
	}
	
	// MARK: Test setup
	
	func setupPopularMoviesListWorker() {
		sut = PopularMoviesListWorker(PopularMoviesNetworkWorkerSpy())
	}
	
	// MARK: Test doubles
	
	class PopularMoviesNetworkWorkerSpy:PopularMoviesNetworkWorker {
		
		var networkCalled = false
		
		override func getPopularMovies(_ page: Int, completion: @escaping (() throws -> PopularMoviesResult) -> Void) {
			
			networkCalled = true
			completion { return Seeds.PopularMovieResultAPI.result }
		}
	}
	
	// MARK: Tests
	
	func testWorker_callsGetPopularMoviesFromNetworkWorker() {
		
		let popularMoviesNetworkSpy = sut.popularMoviesListWorker as! PopularMoviesNetworkWorkerSpy
		
		let expect = expectation(description: "Wait for API result to return")
		sut.getPopularMovies(1) { (result, error) in
			
			expect.fulfill()
		}
		waitForExpectations(timeout: 1.1)
		
		XCTAssertTrue(popularMoviesNetworkSpy.networkCalled)
	}
}
