//
//  PopularMoviesListViewControllerTests.swift
//  Movs
//
//  Created by Tiago Chaves on 18/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Movs
import XCTest

class PopularMoviesListViewControllerTests: XCTestCase {
	
	// MARK: - System under test
	
	var sut: PopularMoviesListViewController!
	var window: UIWindow!
	
	// MARK: Test lifecycle
	
	override func setUp() {
		
		super.setUp()
		window = UIWindow()
		setupPopularMoviesListViewController()
	}
	
	override func tearDown() {
		
		window = nil
		super.tearDown()
	}
	
	// MARK: - Test setup
	
	func setupPopularMoviesListViewController() {
		
		let bundle = Bundle.main
		let storyboard = UIStoryboard(name: "Main", bundle: bundle)
		sut = (storyboard.instantiateViewController(withIdentifier: "PopularMoviesListViewController") as! PopularMoviesListViewController)
	}
	
	func loadView() {
		
		window.addSubview(sut.view)
		RunLoop.current.run(until: Date())
	}
	
	// MARK: - Test doubles
	
	class PopularMoviesListBusinessLogicSpy: PopularMoviesListBusinessLogic {
		
		var getPopularMoviesCalled = false
		var getPopularMoviesRequest:PopularMoviesList.GetPopularMovies.Request!
		
		var storeMovieCalled = false
		var getGenresCalled = false
		var getFilteredMoviesCalled = false
		var getFavoritedMoviesCalled = false
		
		func getPopularMovies(request: PopularMoviesList.GetPopularMovies.Request) {
			getPopularMoviesCalled = true
			getPopularMoviesRequest = request
		}
		
		func storeMovie(request: PopularMoviesList.ShowMovieDetail.Request) {
			storeMovieCalled = true
		}
		
		func getGenres(request: PopularMoviesList.GetGenresList.Request) {
			getGenresCalled = true
		}
		
		func getFilteredMovies(request: PopularMoviesList.FilteredMovies.Request) {
			getFilteredMoviesCalled = true
		}
		
		func getFavoritedMovies(request: PopularMoviesList.RefreshFavoriteStatus.Request) {
			getFavoritedMoviesCalled = true
		}
	}
	
	class RouterSpy:PopularMoviesListRouter{
		
		var routerCalled = false
		
		override func routeToMovieDetail(segue: UIStoryboardSegue?) {
			routerCalled = true
		}
	}
	
	class CollectionViewSpy: UICollectionView {
		
		var reloadDataCalled = false
		
		override func reloadData() {
			
			reloadDataCalled = true
		}
	}
	
	// MARK: Tests
	
	func testVC_whenLoad_callsGetPopularMoviesFirstPageFromInteractor() {
		
		let interactorSpy = PopularMoviesListBusinessLogicSpy()
		sut.interactor = interactorSpy
		
		loadView()
		
		XCTAssertTrue(interactorSpy.getPopularMoviesCalled)
		XCTAssertEqual(interactorSpy.getPopularMoviesRequest.page, 1)
	}
	
	func testVC_whenLoad_callsGetGenreFromInteractor() {
		
		let interactorSpy = PopularMoviesListBusinessLogicSpy()
		sut.interactor = interactorSpy
		
		loadView()
		
		XCTAssertTrue(interactorSpy.getGenresCalled)
	}
}
