////
////  PopularMoviesListPresenterTests.swift
////  Movs
////
////  Created by Tiago Chaves on 18/08/19.
////  Copyright (c) 2019 Tiago Chaves. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import Movs
//import XCTest
//
//class PopularMoviesListPresenterTests: XCTestCase
//{
//  // MARK: Subject under test
//  
//  var sut: PopularMoviesListPresenter!
//  
//  // MARK: Test lifecycle
//  
//  override func setUp()
//  {
//    super.setUp()
//    setupPopularMoviesListPresenter()
//  }
//  
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//  
//  // MARK: Test setup
//  
//  func setupPopularMoviesListPresenter()
//  {
//    sut = PopularMoviesListPresenter()
//  }
//  
//  // MARK: Test doubles
//  
//  class PopularMoviesListDisplayLogicSpy: PopularMoviesListDisplayLogic
//  {
//    var displaySomethingCalled = false
//    
//    func displaySomething(viewModel: PopularMoviesList.Something.ViewModel)
//    {
//      displaySomethingCalled = true
//    }
//  }
//  
//  // MARK: Tests
//  
//  func testPresentSomething()
//  {
//    // Given
//    let spy = PopularMoviesListDisplayLogicSpy()
//    sut.viewController = spy
//    let response = PopularMoviesList.Something.Response()
//    
//    // When
//    sut.presentSomething(response: response)
//    
//    // Then
//    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
//  }
//}
