//
//  MovieDetailsWorker.swift
//  Movs
//
//  Created by Brendoon Ryos on 31/01/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import CoreData

class MovieDetailsWorker {
  
  private let databaseManager: DatabaseManager<CDMovie>
  
  init(databaseManager: DatabaseManager<CDMovie> = DatabaseManager<CDMovie>()) {
    self.databaseManager = databaseManager
  }
  
  func saveFavoriteMovie(request: Movies.Details.Request) {
    let movie = CDMovie(movie: request.movie!, genres: request.genres!, context: databaseManager.viewContext)
    databaseManager.insert(object: movie)
  }
  
  func isFavoriteMovie(request: Movies.Details.Request) -> Bool {
    return databaseManager.exist(id: request.movie!.id)
  }
}
