# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Movs.xcworkspace", scheme: "Movs")
  end

  desc "Run unit test"
  lane :tests do
  run_tests(workspace: "Movs.xcworkspace",
            devices: "iPhone 8",
            scheme: "CI",
	    code_coverage: true)
            
  slather(
      workspace: "Movs.xcworkspace",
      html: true,
      use_bundle_exec: true,
      scheme: "Movs",
      output_directory: "CoverageReport",
      proj: "Movs.xcodeproj",
      ignore: [ "R.generated.swift", "Pods/*"],
      verbose: true,
      show: true)
  end
end
