# frozen_string_literal: true

default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc 'Runs all the tests'
  lane :test do
    scan
    snapshot
  end

  desc 'Ad-hoc build'
  lane :adhoc do
    match(type: 'adhoc')
    gym(export_method: 'ad-hoc')
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  desc 'This will also make sure the profile is up to date'
  lane :beta do
    match(type: 'appstore')
    gym(export_method: 'app-store')
  end

  desc 'Deploy a new version to the App Store'
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  lane :upload_symbols do
    download_dsyms
    upload_symbols_to_sentry(
      auth_token: '1ee015fe8c8811ea90444201c0a8d03b',
      org_slug: 'erick-martins',
      project_slug: 'erick-martins'
    )
  end
end
