# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConcreteApplication' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConcreteApplication
    pod 'Reusable', '~> 4.0'
    pod 'SDWebImage', '~> 4.3.3'
    pod 'SnapKit', '~> 4.2' 

  target 'ConcreteApplicationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConcreteApplicationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
