//
//  ZoomImageInterfaces.swift
//  DataMovie
//
//  Created by Andre on 12/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum ZoomImageNavigationOption {
}

protocol ZoomImageWireframeInterface: WireframeInterface {
    func navigate(to option: ZoomImageNavigationOption)
}

protocol ZoomImageViewInterface: ViewInterface {
    var imgPosterView: UIImageView { get }
}

protocol ZoomImagePresenterInterface: PresenterInterface {
    
}

protocol ZoomImageInteractorInterface: InteractorInterface {
}
