//
//  ZoomImageWireframe.swift
//  DataMovie
//
//  Created by Andre on 12/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ZoomImageWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(type: .zoom)

    // MARK: - Module setup -

    init(moviedetail: MovieViewDetail, transition: ImageAnimatorTransition) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: ZoomImageViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = ZoomImageInteractor()
        let presenter = ZoomImagePresenter(wireframe: self, view: moduleViewController, interactor: interactor, moviedetail: moviedetail)
        moduleViewController.presenter = presenter
        
        if let toDelegate = viewController as? ImageAnimatorDelegate {
            transition.toDelegate = toDelegate
        }
        
    }

}

// MARK: - Extensions -

extension ZoomImageWireframe: ZoomImageWireframeInterface {

    func navigate(to option: ZoomImageNavigationOption) {
    }
}
