//
//  ZoomImageViewController.swift
//  DataMovie
//
//  Created by Andre on 12/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ZoomImageViewController: UIViewController {
    
    @IBOutlet weak var scrollView: UIScrollView!
    @IBOutlet weak var imageView: UIImageView!
    
    // MARK: - Public properties -

    var presenter: ZoomImagePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
        setupScrollView()
    }
	
}

// MARK: - ZoomImageViewInterface -

extension ZoomImageViewController: ZoomImageViewInterface {
    
    var imgPosterView: UIImageView {
        return self.imageView
    }
    
}

//MARK: - UIScrollViewDelegate -

extension ZoomImageViewController: UIScrollViewDelegate {
    
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return imageView
    }
    
}

// MARK: - Functions -

extension ZoomImageViewController {
    
    private func setupScrollView() {
        scrollView.delegate = self
        scrollView.minimumZoomScale = 1.0
        scrollView.maximumZoomScale = 10.0
    }
    
}

// MARK: - ImageAnimatorDelegate -

extension ZoomImageViewController: ImageAnimatorDelegate {
    
    func transitionWillStartWith(animator: ImageAnimatorTransition) { }
    
    func transitionDidEndWith(animator: ImageAnimatorTransition) { }
    
    func referenceImageView(for animator: ImageAnimatorTransition) -> UIImageView? {
        return imageView
    }
    
    func referenceImageViewFrameInTransitioningView(for animator: ImageAnimatorTransition) -> CGRect? {
        view.layoutIfNeeded()
        return imageView.frame
    }
}
