//
//  ZoomImageInteractor.swift
//  DataMovie
//
//  Created by Andre on 12/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ZoomImageInteractor {
}

// MARK: - Extensions -

extension ZoomImageInteractor: ZoomImageInteractorInterface {
}
