//
//  ZoomImagePresenter.swift
//  DataMovie
//
//  Created by Andre on 12/09/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import AlamofireImage

final class ZoomImagePresenter {

    // MARK: - Private properties -

    private unowned var _view: ZoomImageViewInterface
    private var _interactor: ZoomImageInteractorInterface
    private var _wireframe: ZoomImageWireframeInterface
    private var _movieEntity: MovieViewDetail

    // MARK: - Lifecycle -

    init(wireframe: ZoomImageWireframeInterface, view: ZoomImageViewInterface, interactor: ZoomImageInteractorInterface, moviedetail: MovieViewDetail) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        _movieEntity = moviedetail
    }
}

// MARK: - Extensions -

extension ZoomImagePresenter: ZoomImagePresenterInterface {
    
    func viewDidLoad() {
        showImage()
    }
    
}

extension ZoomImagePresenter {
    
    private func showImage() {
        if let posterPath = _movieEntity.posterPath, !posterPath.isEmpty,
            let url = URL(string: TMDBUrl.image(.w500, posterPath).url) {
            _view.imgPosterView.af_setImage(withURL: url, placeholderImage: _movieEntity.poster)
        } else {
            _view.imgPosterView.image = _movieEntity.poster
        }
    }
    
}
