# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Concrete' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'SwiftLint'
    pod 'SDWebImage'
    pod 'Alamofire', '~> 5.0.0-beta.4'

  target 'ConcreteTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'Alamofire', '~> 5.0.0-beta.4'
  end

  target 'ConcreteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
