# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GPSMovies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Cosmos'
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'GPSMoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GPSMoviesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
