project 'AppMovie.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppMovie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Alamofire', '~> 4.8.1'
    pod 'Kingfisher', '~> 4.2'
    pod 'Reusable', '~> 4.0.2'
    
    target :'AppMovieTests' do
        inherit! :search_paths
        pod 'Quick', '1.3.0'
        pod 'Nimble', '7.3.1'
        pod 'Nimble-Snapshots', '6.9.0'
    end

end

