//
//  MovieDetailInteractor.swift
//  Movs
//
//  Created by Tiago Chaves on 14/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
	func getMovieDetail(request: MovieDetail.ShowDetail.Request)
}

protocol MovieDetailDataStore {
	var movie: Movie? { get set }
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
	
	var presenter: MovieDetailPresentationLogic?
	var worker: MovieDetailWorker?
	var movie: Movie?
	
	// MARK: - Show movie detail
	
	func getMovieDetail(request: MovieDetail.ShowDetail.Request) {
		
		if let movie = self.movie {
			let response = MovieDetail.ShowDetail.Response(movie: movie)
			presenter?.presentMovieDetail(response: response)
		}
	}
}
