//
//  MovieDetailPresenter.swift
//  Movs
//
//  Created by Tiago Chaves on 14/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
	func presentMovieDetail(response: MovieDetail.ShowDetail.Response)
	func presentFavoriteStatus(response: MovieDetail.FavoriteMovie.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
	
	weak var viewController: MovieDetailDisplayLogic?
	
	// MARK: - Show Movie Detail
	
	func presentMovieDetail(response: MovieDetail.ShowDetail.Response) {
		
		let movie = response.movie
		
		let viewModel = MovieDetail.ShowDetail.ViewModel(movieDetail: MovieDetailViewModel(title: movie.title ?? "",
																						   backdropUrl: movie.backdrop ?? "",
																						   year: movie.date?.getYear() ?? "",
																						   genres: Genre.getGenresNames(withIds: movie.genre_ids ?? []),
																						   overview: response.movie.overview ?? ""))
		viewController?.displayMovieDetail(viewModel: viewModel)
	}
	
	// MARK: - Favorite Movie
	
	func presentFavoriteStatus(response: MovieDetail.FavoriteMovie.Response) {
		
		viewController?.displayFavoriteStatus(viewModel: MovieDetail.FavoriteMovie.ViewModel(isFavorited: response.isFavorited))
	}
}
