//
//  MovieDetailPresenter.swift
//  Movs
//
//  Created by Tiago Chaves on 14/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
	func presentSomething(response: MovieDetail.Something.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
	
	weak var viewController: MovieDetailDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: MovieDetail.Something.Response) {
		
		let viewModel = MovieDetail.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
