//
//  MovieDetailModels.swift
//  Movs
//
//  Created by Tiago Chaves on 14/08/19.
//  Copyright (c) 2019 Tiago Chaves. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
	
	// MARK: - Show Detail
	
	enum ShowDetail {
		
		struct Request {
			
		}
		
		struct Response {
			let movie: Movie
		}
		
		struct ViewModel {
			let movieDetail: MovieDetailViewModel
		}
	}
}

struct MovieDetailViewModel {
	
	let title		:String
	let backdropUrl	:String
	let year		:String
	let genres		:String
	let overview	:String
}
