//
//  MoviesPresenter.swift
//  Movs
//
//  Created by Brendoon Ryos on 24/01/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviesPresentationLogic {
  func presentMovies(response: Movies.Popular.Response)
  func presentErrorMessage(response: Movies.Popular.Response)
  func presentMovieDetails(response: Movies.Details.Response)
}

class MoviesPresenter: MoviesPresentationLogic {
  weak var viewController: MoviesDisplayLogic?
  
  // MARK: Present Movies
  func presentMovies(response: Movies.Popular.Response) {
    let viewModel = Movies.Popular.ViewModel(data: response.data)
    viewController?.displayMovies(viewModel: viewModel)
  }
  
  // MARK: Present Error Message
  func presentErrorMessage(response: Movies.Popular.Response) {
    let viewModel = Movies.Popular.ViewModel(error: response.error)
    viewController?.displayErrorMessage(viewModel: viewModel)
  }
  
  // MARK: Present Movie Detail
  func presentMovieDetails(response: Movies.Details.Response) {
    let viewModel = Movies.Details.ViewModel(movie: response.movie, genres: response.genres)
    viewController?.displayMovieDetails(viewModel: viewModel)
  }
}
