//
//  MoviesRouter.swift
//  Movs
//
//  Created by Brendoon Ryos on 24/01/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MoviesRoutingLogic {
  func routeToMovieDetails()
}

protocol MoviesDataPassing {
  var dataStore: MoviesDataStore? { get }
}

class MoviesRouter: NSObject, MoviesRoutingLogic, MoviesDataPassing {
  weak var viewController: MoviesViewController?
  var dataStore: MoviesDataStore?
  
  // MARK: Routing
  func routeToMovieDetails() {
    let destinationVC = MovieDetailsViewController()
    var destinationDS = destinationVC.router!.dataStore!
    
    destinationVC.dismissHandler = viewController?.dismissHandler
    passDataToMovieDetails(source: dataStore!, destination: &destinationDS)
    navigateToMovieDetails(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  func navigateToMovieDetails(source: MoviesViewController, destination: MovieDetailsViewController) {
    source.present(destination, animated: true)
  }
  
  // MARK: Passing data
  func passDataToMovieDetails(source: MoviesDataStore, destination: inout MovieDetailsDataStore) {
    destination.movie = source.selectedMovie
    destination.genres = source.selectedGenres
  }
}
