//
//  SeeMovieDetailsRouter.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SeeMovieDetailsRoutingLogic {
  //func routeToSomewhere(_ segue: UIStoryboardSegue? = nil)
}

protocol SeeMovieDetailsDataPassing {
  var dataStore: SeeMovieDetailsDataStore? { get }
}

class SeeMovieDetailsRouter: NSObject, SeeMovieDetailsRoutingLogic, SeeMovieDetailsDataPassing {
  weak var viewController: SeeMovieDetailsViewController?
  var dataStore: SeeMovieDetailsDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(_ segue: UIStoryboardSegue? = nil) {
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SeeMovieDetailsViewController, destination: SomewhereViewController) {
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SeeMovieDetailsDataStore, destination: inout SomewhereDataStore) {
  //  destination.name = source.name
  //}
}
