//
//  SeeMovieDetailsPresenter.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeeMovieDetailsPresentationLogic {
	func presentMovieDetails(with response: SeeMovieDetails.GetMovieDetails.Response)
}

class SeeMovieDetailsPresenter: SeeMovieDetailsPresentationLogic {
	weak var viewController: SeeMovieDetailsDisplayLogic?
	
	// MARK: Do something
	
	func presentMovieDetails(with response: SeeMovieDetails.GetMovieDetails.Response) {
		var image: UIImage? = nil
		if let data = response.image {
			image = UIImage(data: data)?.grayMultiply()
		}
		
		var genresString = ""
		if let genres = response.genres {
			for genre in genres {
				genresString += genre.capitalized + ", "
			}
			
			genresString = String(genresString.dropLast(2))
		}
		
		let release = DateFormatter.localizedString(from: response.releaseDate, dateStyle: .short, timeStyle: .none)
		
		let viewModel = SeeMovieDetails.GetMovieDetails.ViewModel(
			title: response.title,
			image: image,
			genres: genresString,
			release: release,
			overview: response.overview,
			isFavorite: response.isFavorite
		)
		viewController?.displayMovieDetails(with: viewModel)
	}
}
