//
//  SeeMovieDetailsInteractor.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeeMovieDetailsBusinessLogic {
	func getMovieDetails()
}

protocol SeeMovieDetailsDataStore {
	var movie: Movie! { get set }
}

class SeeMovieDetailsInteractor: SeeMovieDetailsBusinessLogic, SeeMovieDetailsDataStore {
	var presenter: SeeMovieDetailsPresentationLogic?
	var movie: Movie!
	
	// MARK: Get Movie Details
	
	func getMovieDetails() {		
		let response = SeeMovieDetails.GetMovieDetails.Response(title: movie.title, image: movie.posterImageData, genres: movie.genres, releaseDate: movie.releaseDate, overview: movie.overview)
		presenter?.presentMovieDetails(with: response)
	}
}
