//
//  SeeMovieDetailsRouter.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SeeMovieDetailsRoutingLogic {
	func routeToListMovies()
}

protocol SeeMovieDetailsDataPassing {
	var dataStore: SeeMovieDetailsDataStore? { get }
}

class SeeMovieDetailsRouter: NSObject, SeeMovieDetailsRoutingLogic, SeeMovieDetailsDataPassing {
	weak var viewController: SeeMovieDetailsViewController?
	var dataStore: SeeMovieDetailsDataStore?
	
	// MARK: Routing
	
	func routeToListMovies() {
		guard let destinationVC = viewController?.navigationController?.viewControllers.first as? ListMoviesViewController else { return }
		var destinationDS = destinationVC.router!.dataStore!
		passDataToListMovies(source: dataStore!, destination: &destinationDS)
	}
	// MARK: Passing data
	
	func passDataToListMovies(source: SeeMovieDetailsDataStore, destination: inout ListMoviesDataStore) {
	  destination.isFavorite = source.isFavorite
	}
}
