//
//  SeeMovieDetailsInteractor.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeeMovieDetailsBusinessLogic {
	func doSomething(request: SeeMovieDetails.Something.Request)
}

protocol SeeMovieDetailsDataStore {
	var movie: Movie! { get set }
}

class SeeMovieDetailsInteractor: SeeMovieDetailsBusinessLogic, SeeMovieDetailsDataStore {
	var presenter: SeeMovieDetailsPresentationLogic?
	var worker: SeeMovieDetailsWorker?
	var movie: Movie!
	
	// MARK: Do something
	
	func doSomething(request: SeeMovieDetails.Something.Request) {
		worker = SeeMovieDetailsWorker()
		worker?.doSomeWork()
		
		let response = SeeMovieDetails.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
