//
//  SeeMovieDetailsViewController.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeeMovieDetailsDisplayLogic: class {
	func displaySomething(viewModel: SeeMovieDetails.Something.ViewModel)
}

class SeeMovieDetailsViewController: UIViewController, SeeMovieDetailsDisplayLogic {
	var interactor: SeeMovieDetailsBusinessLogic?
	var router: (NSObjectProtocol & SeeMovieDetailsRoutingLogic & SeeMovieDetailsDataPassing)?
	
	// MARK: Outlets
	
	@IBOutlet weak var backgroundImageView: UIImage!
	@IBOutlet weak var titleLabel: UILabel!
	@IBOutlet weak var releaseDateLabel: UILabel!
	@IBOutlet weak var genresLabel: UILabel!
	@IBOutlet weak var overviewLabel: UILabel!
	
	// MARK: Object lifecycle
	
	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}
	
	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}
	
	// MARK: Setup
	
	private func setup() {
		let viewController = self
		let interactor = SeeMovieDetailsInteractor()
		let presenter = SeeMovieDetailsPresenter()
		let router = SeeMovieDetailsRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
		router.dataStore = interactor
	}
	
	// MARK: Routing
	
	override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
		if let scene = segue.identifier {
			let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
			if let router = router, router.responds(to: selector) {
				router.perform(selector, with: segue)
			}
		}
	}
	
	// MARK: View lifecycle
	
	override func viewDidLoad() {
		super.viewDidLoad()
		doSomething()
	}
	
	// MARK: Do something
	
	//@IBOutlet weak var nameTextField: UITextField!
	
	func doSomething() {
		let request = SeeMovieDetails.Something.Request()
		interactor?.doSomething(request: request)
	}
	
	func displaySomething(viewModel: SeeMovieDetails.Something.ViewModel) {
		//nameTextField.text = viewModel.name
	}
}
