//
//  SeeMovieDetailsPresenter.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SeeMovieDetailsPresentationLogic {
	func presentSomething(response: SeeMovieDetails.Something.Response)
}

class SeeMovieDetailsPresenter: SeeMovieDetailsPresentationLogic {
	weak var viewController: SeeMovieDetailsDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: SeeMovieDetails.Something.Response) {
		let viewModel = SeeMovieDetails.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
