//
//  SeeMovieDetailsModels.swift
//  Movs
//
//  Created by Lucas Ferraço on 19/09/18.
//  Copyright (c) 2018 Lucas Ferraço. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SeeMovieDetails {
	//MARK:- Get Movie Details -
	
	enum GetMovieDetails {
		struct Response {
			var title: String
			var image: Data?
			var genres: [String]?
			var releaseDate: Date
			var overview: String
			var isFavorite: Bool
		}
		
		struct ViewModel {
			var title: String
			var image: UIImage?
			var genres: String
			var release: String
			var overview: String
			var isFavorite: Bool
		}
	}
}
