//
//  FilterInteractor.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 01/11/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterBusinessLogic {
    func fetchYearsAndGenres()
    func setSelected(year: String, genre: String)
}

protocol FilterDataStore {
    var genres: [String] { get set }
    var years: [String] { get set }
    var selectedYear: String { get set }
    var selectedGenre: String { get set }
}

class FilterInteractor: FilterBusinessLogic, FilterDataStore {
    var genres: [String] = []
    var years: [String] = []
    var selectedGenre = ""
    var selectedYear = ""
    var presenter: FilterPresentationLogic?
    
    func fetchYearsAndGenres() {
        presenter?.present(years: self.years, genres: self.genres)
    }
    
    func setSelected(year: String, genre: String) {
        self.selectedYear = year
        self.selectedGenre = genre
    }
}
