//
//  FilterPresenter.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 01/11/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FilterPresentationLogic {
  func presentSomething(response: Filter.Something.Response)
    func present(years: [String], genres: [String])
}

class FilterPresenter: FilterPresentationLogic {
  weak var viewController: FilterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Filter.Something.Response) {
    let viewModel = Filter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func present(years: [String], genres: [String]) {
        viewController?.display(years: years, genres: genres)
    }
}
