# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie
  pod 'Moya'
  pod 'Nuke'
  pod 'SnapKit'
  pod 'SwiftDate'

  target 'MovieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
