//
//  HomePresenter.swift
//  DataMovie
//
//  Created by Andre on 12/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomePresenter {

    // MARK: - Private properties -

    private unowned var _view: HomeViewInterface
    private var _interactor: HomeInteractorInterface
    private var _wireframe: HomeWireframeInterface
    
    private let _tabItems: [HomeTabItem] = [.movieList]

    // MARK: - Lifecycle -

    init(wireframe: HomeWireframeInterface, view: HomeViewInterface, interactor: HomeInteractorInterface) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    
    func setupTabs() {
        var viewControllers = [UIViewController]()
        _tabItems.forEach() { tabItem in
            let viewController = tabItem.viewController
            viewController.tabBarItem = tabItem.tabBarItem
            viewControllers.append(viewController)
        }
        _view.setTabViewControllers(viewControllers)
    }
    
}
