//
//  HomeViewController.swift
//  DataMovie
//
//  Created by Andre on 12/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: UITabBarController {

    // MARK: - Public properties -

    var presenter: HomePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        initialSetup()
    }
	
}

// MARK: - Functions -

extension HomeViewController {
    
    private func initialSetup() {
        presenter.setupTabs()
    }
    
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
    
    func setTabViewControllers(_ viewControllers: [UIViewController]) {
        setViewControllers(viewControllers, animated: true)
    }
    
}
