//
//  HomeInterfaces.swift
//  DataMovie
//
//  Created by Andre on 12/08/2018.
//  Copyright (c) 2018 Andre. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum HomeNavigationOption {
}

protocol HomeWireframeInterface: WireframeInterface {
}

protocol HomeViewInterface: ViewInterface {
    func setTabViewControllers(_ viewControllers: [UIViewController])
}

protocol HomePresenterInterface: PresenterInterface {
    func setupTabs()
}

protocol HomeInteractorInterface: InteractorInterface {
}
