//
//  MovieDetailInteractor.swift
//  concreto-filmes
//
//  Created by Leonel Menezes on 23/10/18.
//  Copyright (c) 2018 Leonel Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
    func toggleFavoriteMovie()
}

protocol MovieDetailDataStore {
    var movie: Movie? {get set}
}

class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
    var movie: Movie?
    var presenter: MovieDetailPresentationLogic?
    var worker: MovieDetailWorker?
    let realm = RealmService.shared.realm
    
    func toggleFavoriteMovie() {
        if let movie = movie {
            if let movieAlreadyInRealm = realm?.object(ofType: MovieRealm.self, forPrimaryKey: movie.id) {
                RealmService.shared.delete(movieAlreadyInRealm)
            } else {
                let movieRealm = MovieRealm(movie: movie)
                RealmService.shared.create(movieRealm)
            }
        }
    }
}
