disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - weak_delegate
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods