# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movies' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'
  
  target 'moviesTests' do
    inherit! :search_paths
    
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
  end

end
