# Uncomment the next line to define a global platform for your project
platform :ios, '11.4'

target 'Movs Challenge Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for Movs Challenge Project

  pod 'SteviaLayout'

  target 'Movs Challenge ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
