# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movies Concrete' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movies Concrete
  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 4.7'
  pod 'ObjectMapper'
  pod 'AlamofireObjectMapper'
  pod 'Kingfisher', '~> 5.0'

end
